In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
sf_building_permits = pd.read_csv("/Users/arsheenkhatib/Desktop/datasets/Building_Permits.csv", error_bad_lines=False)

In [3]:
pd.set_option("display.max_columns", 50)
sf_building_permits

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,Unit,Unit Suffix,Description,Current Status,Current Status Date,Filed Date,Issued Date,Completed Date,First Construction Document Date,Structural Notification,Number of Existing Stories,Number of Proposed Stories,Voluntary Soft-Story Retrofit,Fire Only Permit,Permit Expiration Date,Estimated Cost,Revised Cost,Existing Use,Existing Units,Proposed Use,Proposed Units,Plansets,TIDF Compliance,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,NaN,NaN,"ground fl facade: to erect illuminated, electr...",expired,12/21/2017,05/06/2015,11/09/2015,NaN,11/09/2015,NaN,6.0,NaN,NaN,NaN,11/03/2016,4000.00,4000.00,tourist hotel/motel,143.0,NaN,NaN,2.0,NaN,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,0.0,NaN,remove (e) awning and associated signs.,issued,08/03/2017,04/19/2016,08/03/2017,NaN,08/03/2017,NaN,7.0,NaN,NaN,NaN,12/03/2017,1.00,500.00,tourist hotel/motel,NaN,NaN,NaN,2.0,NaN,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,NaN,NaN,installation of separating wall,withdrawn,09/26/2017,05/27/2016,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,20000.00,NaN,retail sales,39.0,retail sales,39.0,2.0,NaN,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,0.0,NaN,repair dryrot & stucco at front of bldg.,complete,07/24/2017,11/07/2016,07/18/2017,07/24/2017,07/18/2017,NaN,2.0,2.0,NaN,NaN,07/13/2018,2000.00,2000.00,1 family dwelling,1.0,1 family dwelling,1.0,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,NaN,NaN,demolish retail/office/commercial 3-story buil...,issued,12/01/2017,11/28/2016,12/01/2017,NaN,11/20/2017,NaN,3.0,NaN,NaN,NaN,12/01/2018,100000.00,100000.00,retail sales,NaN,NaN,NaN,2.0,NaN,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
5,201706149344,8,otc alterations permit,06/14/2017,4105,009,800,NaN,Indiana,St,NaN,NaN,evac maps,issued,07/06/2017,06/14/2017,07/06/2017,NaN,07/06/2017,NaN,5.0,5.0,NaN,Y,07/01/2018,4000.00,4000.00,apartments,326.0,apartments,326.0,2.0,NaN,1.0,constr type 1,1.0,constr type 1,NaN,10.0,Potrero Hill,94107.0,"(37.75922331346539, -122.39170402628598)",1466911170855
6,201706300814,8,otc alterations permit,06/30/2017,1739,020,1291,NaN,11th,Av,0.0,NaN,re-roofing,complete,07/12/2017,06/30/2017,06/30/2017,07/12/2017,06/30/2017,NaN,3.0,3.0,NaN,NaN,06/25/2018,12000.00,12000.00,apartments,5.0,apartments,5.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Inner Sunset,94122.0,"(37.764145640138565, -122.46875112470363)",1468970403692
7,M803667,8,otc alterations permit,06/30/2017,4789,014,1465,NaN,Revere,Av,NaN,NaN,streetspace,issued,06/30/2017,06/30/2017,06/30/2017,NaN,06/30/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,Bayview Hunters Point,94124.0,"(37.73005099023611, -122.38784938916618)",1469035175050
8,M804227,8,otc alterations permit,07/05/2017,1212,054,2094,NaN,Fell,St,NaN,NaN,street space permit,issued,07/05/2017,07/05/2017,07/05/2017,NaN,07/05/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.772393498502595, -122.45231466824669)",1469198253772
9,M804767,8,otc alterations permit,07/06/2017,1259,016,89,NaN,Alpine,Tr,NaN,NaN,street space,issued,07/06/2017,07/06/2017,07/06/2017,NaN,07/06/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Haight Ashbury,94117.0,"(37.7691724293766, -122.43734859051908)",146932394171
10,M805287,8,otc alterations permit,07/06/2017,3541,001,106,NaN,Sanchez,St,NaN,NaN,street space,issued,07/06/2017,07/06/2017,07/06/2017,NaN,07/06/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.767349757757145, -122.43140682973024)",1469445246849
11,M805907,8,otc alterations permit,07/07/2017,0829,021,675,NaN,Fell,St,NaN,NaN,street space,issued,07/07/2017,07/07/2017,07/07/2017,NaN,07/07/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102.0,"(37.774914087334544, -122.42886839796792)",146961582526
12,M806447,8,otc alterations permit,07/10/2017,6537,023,4082,NaN,25th,St,NaN,NaN,street space,issued,07/10/2017,07/10/2017,07/10/2017,NaN,07/10/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.75006779619502, -122.43127350268124)",1469781206718
13,201707252846,8,otc alterations permit,07/25/2017,6589,002R,681,NaN,27th,St,NaN,NaN,remove and replace landscape wall,filed,07/25/2017,07/25/2017,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,30000.00,0.00,1 family dwelling,1.0,1 family dwelling,1.0,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Noe Valley,94131.0,"(37.7462205625642, -122.4353484860549)",1471799208305
14,M813729,8,otc alterations permit,07/26/2017,1049,027,2761,NaN,Pine,St,NaN,NaN,street space,issued,07/26/2017,07/26/2017,07/26/2017,NaN,07/26/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Pacific Heights,94115.0,"(37.78676200041077, -122.44124093333335)",147203988249
15,M813907,8,otc alterations permit,07/27/2017,0243,043,840,NaN,Powell,St,301.0,NaN,street space,issued,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Chinatown,94108.0,"(37.7926690651263, -122.40883941791454)",147208763456
16,M813967,8,otc alterations permit,07/27/2017,0268,008,220,NaN,Montgomery,St,NaN,NaN,street space permit,issued,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Financial District/South Beach,94104.0,"(37.79130641988351, -122.40198579459195)",147211866168
17,M814148,8,otc alterations permit,07/27/2017,3621,097,3707,NaN,21st,St,0.0,NaN,street space & sidewalk repair,issued,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.75607840165479, -122.43041143390109)",1472184412108
18,201707283165,8,otc alterations permit,07/28/2017,0472,042,1307,NaN,Bay,St,1.0,NaN,soft story ordinance sf building code chptr 34...,filed,07/28/2017,07/28/2017,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,NaN,75000.00,0.00,apartments,6.0,apartments,6.0,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.8035183252307, -122.42863180996076)",1472277302360
19,M814368,8,otc alterations permit,07/28/2017,2659,001,263,NaN,Corbett,Av,0.0,NaN,street space,issued,07/28/2017,07/28/2017,07/28/2017,NaN,07/28/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.761092365437214, -122.44402154957145)",1472295408612
20,M814967,8,otc alterations permit,07/31/2017,1176,068,1624,NaN,Fulton,St,NaN,NaN,street space,issued,07/31/2017,07/31/2017,07/31/2017,NaN,07/31/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77640228859421, -122.44361679686382)",1472619503582
21,201708013476,8,otc alterations permit,08/01/2017,6529,010,3410,NaN,26th,St,NaN,NaN,repair fire damage to comply with nov #201551241.,filed,08/01/2017,08/01/2017,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,100000.00,0.00,2 family dwelling,2.0,2 family dwelling,2.0,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Mission,94110.0,"(37.74914175355125, -122.41849211166853)",1472727381751
22,201708013544,3,additions alterations or repairs,08/01/2017,0074,043,2150,NaN,Taylor,St,NaN,NaN,"soft story retrofit per sfebc chapter 4d, asce...",filed,08/01/2017,08/01/2017,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,100000.00,NaN,apartments,6.0,apartments,6.0,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Russian Hill,94133.0,"(37.802405951667645, -122.41446286561653)",147281357792
23,M816927,8,otc alterations permit,08/07/2017,0941,012,2824,NaN,Filbert,St,NaN,NaN,street space,issued,08/07/2017,08/07/2017,08/07/2017,NaN,08/07/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Marina,94123.0,"(37.79697456740493, -122.44615769723546)",147359384812
24,201708084249,8,otc alterations permit,08/08/2017,0542,039,1,NaN,Charlton,Ct,NaN,NaN,re-roofing,issued,08/08/2017,08/08/2017,08/08/2017,NaN,08/08/2017,NaN,4.0,4.0,NaN,NaN,08/08/2018,64650.00,64650.00,apartments,9.0,apartments,9.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.79739093461306, -122.43127133823367)",1473796372030
25,201708165014,8,otc alterations permit,08/16/2017,1824,006,1435,NaN,29th,Av,NaN,NaN,re-roofing,issued,08/16/2017,08/16/2017,08/16/2017,NaN,08/16/2017,NaN,2.0,2.0,NaN,NaN,02/16/2018,7000.00,7000.00,1 family dwelling,1.0,1 family dwelling,1.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,4.0,Sunset/Parkside,94122.0,"(37.76052279949518, -122.4879889739165)",1474841115935
26,M820728,8,otc alterations permit,08/18/2017,1449,006,331,NaN,17th,Av,NaN,NaN,street space,issued,08/18/2017,08/18/2017,08/18/2017,NaN,08/18/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121.0,"(37.78177022745135, -122.47658979438802)",1475223100163
27,M821207,8,otc alterations permit,08/21/2017,1193,024,120,NaN,Shrader,St,NaN,NaN,street space & sidewalk repair,issued,08/21/2017,08/21/2017,08/21/2017,NaN,08/21/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77371007080848, -122.45243180846707)",147537591942
28,M821268,8,otc alterations permit,08/21/2017,1851,012,1512,NaN,06th,Av,NaN,NaN,street space,issued,08/21/2017,08/21/2017,08/21/2017,NaN,08/21/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,Inner Sunset,94122.0,"(37.760252335082875, -122.4625393396095)",1475405117215
29,M821847,8,otc alterations permit,08/22/2017,0326,001,165,NaN,Powell,St,NaN,NaN,street space,issued,08/22/2017,08/22/2017,08/22/2017,NaN,08/22/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78625524960107, -122.40834431815433)",1475605447747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,M893328,8,otc alterations permit,02/23/2018,0025,024,888,NaN,North Point,St,NaN,NaN,street space permit,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Russian Hill,94109.0,"(37.8057495627139, -122.42181538597318)",1498327347381
198871,M893347,8,otc alterations permit,02/23/2018,1253,001,701,NaN,Clayton,St,NaN,NaN,street space,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Haight Ashbury,94117.0,"(37.76869660680249, -122.44864582118123)",1498328241068
198872,201802232165,8,otc alterations permit,02/23/2018,3543,012,2123,NaN,Market,St,NaN,NaN,2016 cebc chapter 4 {bs}403.9 voluntary seismi...,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,10000.00,0.00,retail sales,NaN,retail sales,NaN,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Castro/Upper Market,94114.0,"(37.76682151637876, -122.42926240167795)",1498329423799
198873,201802232166,8,otc alterations permit,02/23/2018,5723,041,100,NaN,Tompkins,Av,0.0,NaN,to obtain final inspection for work approved u...,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,2.0,2.0,NaN,NaN,06/23/2018,1.00,1.00,1 family dwelling,1.0,1 family dwelling,1.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Bernal Heights,94110.0,"(37.73708421334594, -122.4157759256698)",1498330475722
198874,201802232106,8,otc alterations permit,02/23/2018,6592,023,336,NaN,Duncan,St,0.0,NaN,"replace tile in (e) shower as per kind, replac...",issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,3.0,3.0,NaN,NaN,08/23/2018,10000.00,15000.00,apartments,3.0,apartments,3.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Noe Valley,94131.0,"(37.746231746880696, -122.4285179313817)",1498331399024
198875,201802232167,8,otc alterations permit,02/23/2018,0807,010,580,NaN,Hayes,St,NaN,NaN,modify fire alarm and 2 way communication sys...,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,1.00,0.00,NaN,NaN,apartments,29.0,2.0,NaN,NaN,NaN,1.0,constr type 1,NaN,5.0,Hayes Valley,94102.0,"(37.776756688343944, -122.4260292019233)",149833282001
198876,M893367,8,otc alterations permit,02/23/2018,1213,013,500,NaN,Stanyan,St,NaN,NaN,street space,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77277103274044, -122.45392960440346)",149833392632
198877,201802232169,8,otc alterations permit,02/23/2018,7103,020,91,NaN,Lobos,St,NaN,NaN,to comply with nov 201708341 - replace new han...,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,2.0,2.0,NaN,NaN,06/23/2018,1000.00,1000.00,1 family dwelling,1.0,1 family dwelling,1.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Oceanview/Merced/Ingleside,94112.0,"(37.7146765393289, -122.45557353560899)",1498334221586
198878,201802232170,8,otc alterations permit,02/23/2018,3641,016,3134,NaN,24th,St,0.0,NaN,to comply with nov 20174461 & 201714471 item #...,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,20000.00,0.00,apartments,4.0,apartments,4.0,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Mission,94110.0,"(37.752661001157854, -122.41485533400166)",1498335409431
198879,201802232171,8,otc alterations permit,02/23/2018,6082,009,350,NaN,Paris,St,NaN,NaN,install 1300 sq ft vinyl siding to left side &...,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,2.0,2.0,NaN,NaN,08/23/2018,18453.12,18453.12,1 family dwelling,1.0,1 family dwelling,1.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Excelsior,94112.0,"(37.72324934238285, -122.43409219261636)",1498336195616
198880,M893387,8,otc alterations permit,02/23/2018,1841,025D,1442,NaN,Funston,Av,NaN,NaN,street space,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,Inner Sunset,94122.0,"(37.76117190796411, -122.47007880106999)",1498337116842
198881,M893407,8,otc alterations permit,02/23/2018,0018,004,2300,NaN,Stockton,St,NaN,NaN,street space & sidewalk repair,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,North Beach,94133.0,"(37.80747140583783, -122.41024025753224)",1498338347099
198882,201802232172,8,otc alterations permit,02/23/2018,6021,001B,730,NaN,Excelsior,Av,NaN,NaN,to obtain final inspection for work approved u...,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,2.0,2.0,NaN,NaN,06/23/2018,1.00,1.00,1 family dwelling,1.0,1 family dwelling,1.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Excelsior,94112.0,"(37.723206757170836, -122.42763728105176)",1498339194341
198883,M893427,8,otc alterations permit,02/23/2018,0315,021,377,NaN,Geary,St,NaN,NaN,street space,issued,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78696971667916, -122.40936701144197)",149834069380
198884,M893447,8,otc alterations permit,02/23/2018,3504,030,1699,NaN,Market,St,NaN,NaN,street space,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,Mission,94103.0,"(37.77217130976155, -122.42193576313322)",1498341156230
198885,201802232173,8,otc alterations permit,02/23/2018,2150,001A,2007,NaN,30th,Av,NaN,NaN,revision to pa 2017-1128-4886 - reconfigure 2n...,filed,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,5000.00,0.00,1 family dwelling,1.0,1 family dwelling,1.0,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,4.0,Sunset/Parkside,94116.0,"(37.74976582284573, -122.48824447038214)",1498342127659
198886,201709066971,3,additions alterations or repairs,09/06/2017,0999,025,3191,NaN,Washington,St,NaN,NaN,compliance w/ mandatory seismic retrofit progr...,approved,01/11/2018,09/06/2017,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,65000.00,65000.00,apartments,6.0,apartments,6.0,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1477559238559
198887,201710040362,8,otc alterations permit,10/04/2017,0750,001,1521,NaN,Eddy,St,NaN,NaN,(n) accessible ramp at entry (inside bldg). re...,complete,12/06/2017,10/04/2017,11/03/2017,12/06/2017,11/03/2017,NaN,4.0,4.0,NaN,NaN,11/03/2018,30000.00,30000.00,food/beverage hndlng,191.0,food/beverage hndlng,191.0,2.0,NaN,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN,1482126434174
198888,201710110995,8,otc alterations permit,10/11/2017,0726,019,1410,NaN,Steiner,St,NaN,NaN,apt m2ph-1e: remove & replace kitchen adn bath...,complete,12/07/2017,10/11/2017,10/12/2017,12/07/2017,10/12/2017,NaN,9.0,9.0,NaN,NaN,10/12/2018,18000.00,30000.00,apartments,78.0,apartments,78.0,0.0,NaN,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN,1483035367814
198889,201710242114,8,otc alterations permit,10/24/2017,1654,035,748,NaN,12th,Av,NaN,NaN,reroofing,complete,12/05/2017,10/24/2017,10/24/2017,12/05/2017,10/24/2017,NaN,1.0,1.0,NaN,NaN,04/24/2018,20000.00,20000.00,1 family dwelling,1.0,1 family dwelling,1.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1484587273155
198890,201711274822,3,additions alterations or repairs,11/27/2017,3803,001,185,NaN,Berry,St,NaN,NaN,"1st flr: suite 1000, construction of primary a...",filed,11/27/2017,11/27/2017,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN,NaN,750000.00,750000.00,office,NaN,office,NaN,2.0,NaN,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN,1488352388160
198891,201711274844,8,otc alterations permit,11/27/2017,0766,008,590,NaN,Van Ness,Av,NaN,NaN,revision to 201608316525 for reflected ceiling,issued,12/08/2017,11/27/2017,12/08/2017,NaN,12/08/2017,NaN,2.0,2.0,NaN,NaN,04/08/2018,1.00,1.00,food/beverage hndlng,0.0,food/beverage hndlng,0.0,2.0,NaN,3.0,constr type 3,3.0,constr type 3,NaN,NaN,NaN,NaN,NaN,148838081446
198892,201712045380,8,otc alterations permit,12/04/2017,1180,021,1543,NaN,Mcallister,St,NaN,NaN,soft story per sfbc chapter 4d 2016 iebc,issued,01/16/2018,12/04/2017,01/16/2018,NaN,01/16/2018,NaN,3.0,3.0,NaN,NaN,01/16/2019,55000.00,38000.00,apartments,5.0,apartments,5.0,2.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,148916691540
198893,201712055472,8,otc alterations permit,12/05/2017,1000,014,3018,NaN,Clay,St,NaN,NaN,bathtub & shower tile replacement.,complete,01/22/2018,12/05/2017,12/05/2017,01/22/2018,12/05/2017,NaN,3.0,3.0,NaN,NaN,04/05/2018,2800.00,2800.00,apartments,3.0,apartments,3.0,0.0,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489281258414

In [4]:
#frequency of missing values in each columns
percent_null = sf_building_permits.isnull().sum()
(percent_null*100)/len(sf_building_permits)

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Number Suffix                      98.885872
Street Name                                0.000000
Street Suffix                              1.391654
Unit                                      85.178984
Unit Suffix                               99.014077
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                7.511312
Completed Date                            51.135747
First Construction Document Date           7.514329
Structural Notification                   96.519859
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Voluntary Soft-Story Retrofit             99.982403
Fire Only Permit                          90.534439
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
TIDF Compliance                           99.998994
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Site Permit                               97.305681
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

In [5]:
#drop columns with missing data >70%
sf_building_permits = sf_building_permits.drop(['Street Number Suffix','Unit','Unit Suffix','Structural Notification',
                                               'Voluntary Soft-Story Retrofit','Fire Only Permit',
                                                'TIDF Compliance','Site Permit'], axis =1)

In [6]:
#frequency of missing values in each columns
percent_null = sf_building_permits.isnull().sum()
(percent_null*100)/len(sf_building_permits)

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Name                                0.000000
Street Suffix                              1.391654
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                7.511312
Completed Date                            51.135747
First Construction Document Date           7.514329
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

In [7]:
#sf_building_permits.loc[7]

In [8]:
#Number of distinct values under each column in the dataframe
sf_building_permits.T.apply(lambda x: x.nunique(), axis=1)

Permit Number                             181495
Permit Type                                    8
Permit Type Definition                         8
Permit Creation Date                        1291
Block                                       4896
Lot                                         1055
Street Number                               5099
Street Name                                 1704
Street Suffix                                 21
Description                               134272
Current Status                                14
Current Status Date                         1307
Filed Date                                  1288
Issued Date                                 1289
Completed Date                              1300
First Construction Document Date            1288
Number of Existing Stories                    64
Number of Proposed Stories                    64
Permit Expiration Date                      2232
Estimated Cost                             11395
Revised Cost                               12629
Existing Use                                  93
Existing Units                               348
Proposed Use                                  94
Proposed Units                               368
Plansets                                       8
Existing Construction Type                     5
Existing Construction Type Description         5
Proposed Construction Type                     5
Proposed Construction Type Description         5
Supervisor District                           11
Neighborhoods - Analysis Boundaries           41
Zipcode                                       27
Location                                   57604
Record ID                                 198900
dtype: int64

In [9]:
#List the data types of each of the columns
sf_building_permits.dtypes

Permit Number                              object
Permit Type                                 int64
Permit Type Definition                     object
Permit Creation Date                       object
Block                                      object
Lot                                        object
Street Number                               int64
Street Name                                object
Street Suffix                              object
Description                                object
Current Status                             object
Current Status Date                        object
Filed Date                                 object
Issued Date                                object
Completed Date                             object
First Construction Document Date           object
Number of Existing Stories                float64
Number of Proposed Stories                float64
Permit Expiration Date                     object
Estimated Cost                            float64
Revised Cost                              float64
Existing Use                               object
Existing Units                            float64
Proposed Use                               object
Proposed Units                            float64
Plansets                                  float64
Existing Construction Type                float64
Existing Construction Type Description     object
Proposed Construction Type                float64
Proposed Construction Type Description     object
Supervisor District                       float64
Neighborhoods - Analysis Boundaries        object
Zipcode                                   float64
Location                                   object
Record ID                                   int64
dtype: object

In [10]:
#frequency of missing values in each columns
percent_null = sf_building_permits.isnull().sum()
(percent_null*100)/len(sf_building_permits)

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Name                                0.000000
Street Suffix                              1.391654
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                7.511312
Completed Date                            51.135747
First Construction Document Date           7.514329
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

In [11]:
#we see that the completed date only coincides with the completed status. NMAR
#51% buildings are incomplete
sf_building_permits[['Current Status','Completed Date']]

       Current Status Completed Date
0             expired            NaN
1              issued            NaN
2           withdrawn            NaN
3            complete     07/24/2017
4              issued            NaN
5              issued            NaN
6            complete     07/12/2017
7              issued            NaN
8              issued            NaN
9              issued            NaN
10             issued            NaN
11             issued            NaN
12             issued            NaN
13              filed            NaN
14             issued            NaN
15             issued            NaN
16             issued            NaN
17             issued            NaN
18              filed            NaN
19             issued            NaN
20             issued            NaN
21              filed            NaN
22              filed            NaN
23             issued            NaN
24             issued            NaN
25             issued            NaN
26             issued            NaN
27             issued            NaN
28             issued            NaN
29             issued            NaN
...               ...            ...
198870         issued            NaN
198871         issued            NaN
198872          filed            NaN
198873         issued            NaN
198874         issued            NaN
198875          filed            NaN
198876         issued            NaN
198877         issued            NaN
198878          filed            NaN
198879         issued            NaN
198880         issued            NaN
198881         issued            NaN
198882         issued            NaN
198883         issued            NaN
198884          filed            NaN
198885          filed            NaN
198886       approved            NaN
198887       complete     12/06/2017
198888       complete     12/07/2017
198889       complete     12/05/2017
198890          filed            NaN
198891         issued            NaN
198892         issued            NaN
198893       complete     01/22/2018
198894         issued            NaN
198895         issued            NaN
198896         issued            NaN
198897         issued            NaN
198898         issued            NaN
198899         issued            NaN

[198900 rows x 2 columns]

In [12]:
#making sure that there is no missing data other than that which we already expect
list1=[]
for index in range(len(sf_building_permits)):
    if (type(sf_building_permits['Completed Date'][index]) == float):
        list1.append(index)

In [13]:
#percentage of missing values is exactly what we expect. Hence no unexpected missing data.
not_missed = 0
for index in list1:
    if (sf_building_permits['Current Status'][index]) == "complete":
        print(index,sf_building_permits['Issued Date'][index],sf_building_permits['First Construction Document Date'][index])
    elif not (sf_building_permits['Current Status'][index]) == "complete":
        not_missed+=1
print("missing vlaues: {}".format((not_missed*100)/len(sf_building_permits)))

missing vlaues: 51.13574660633484

In [14]:
#impute the incomplete values with "Not Complete"
sf_building_permits = sf_building_permits.fillna(value={'Completed Date':'Incomplete'})

In [15]:
#frequency of missing values in each columns
percent_null = sf_building_permits.isnull().sum()
(percent_null*100)/len(sf_building_permits)

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Name                                0.000000
Street Suffix                              1.391654
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                7.511312
Completed Date                             0.000000
First Construction Document Date           7.514329
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

In [58]:
#checked the street name types and found that not all streets need a suffix

#for i in range(len(sf_building_permits['Street Suffix'])):
#    if type(sf_building_permits['Street Suffix'][i])==float:
#        print("street name: {}".format(sf_building_permits['Street Name'][i]))

In [59]:
#we see that the missing data corresponds to status where the data hasn't reached the starting phase yet
#this means that the data is missing for 'appeal', 'approved','filed','withdrawn','cancelled'
sf_building_permits[['Current Status','Issued Date']]

       Current Status     Issued Date
0             expired      11/09/2015
1              issued      08/03/2017
2           withdrawn  Not Issued yet
3            complete      07/18/2017
4              issued      12/01/2017
5              issued      07/06/2017
6            complete      06/30/2017
7              issued      06/30/2017
8              issued      07/05/2017
9              issued      07/06/2017
10             issued      07/06/2017
11             issued      07/07/2017
12             issued      07/10/2017
13              filed  Not Issued yet
14             issued      07/26/2017
15             issued      07/27/2017
16             issued      07/27/2017
17             issued      07/27/2017
18              filed  Not Issued yet
19             issued      07/28/2017
20             issued      07/31/2017
21              filed  Not Issued yet
22              filed  Not Issued yet
23             issued      08/07/2017
24             issued      08/08/2017
25             issued      08/16/2017
26             issued      08/18/2017
27             issued      08/21/2017
28             issued      08/21/2017
29             issued      08/22/2017
...               ...             ...
198870         issued      02/23/2018
198871         issued      02/23/2018
198872          filed  Not Issued yet
198873         issued      02/23/2018
198874         issued      02/23/2018
198875          filed  Not Issued yet
198876         issued      02/23/2018
198877         issued      02/23/2018
198878          filed  Not Issued yet
198879         issued      02/23/2018
198880         issued      02/23/2018
198881         issued      02/23/2018
198882         issued      02/23/2018
198883         issued      02/23/2018
198884          filed  Not Issued yet
198885          filed  Not Issued yet
198886       approved  Not Issued yet
198887       complete      11/03/2017
198888       complete      10/12/2017
198889       complete      10/24/2017
198890          filed  Not Issued yet
198891         issued      12/08/2017
198892         issued      01/16/2018
198893       complete      12/05/2017
198894         issued      12/05/2017
198895         issued      12/05/2017
198896         issued      12/06/2017
198897         issued      12/06/2017
198898         issued      12/06/2017
198899         issued      12/07/2017

[198900 rows x 2 columns]

In [60]:
#we have data for 'complete','issued', and 'expired'

for i in range(len(sf_building_permits)):
    if type(sf_building_permits['Issued Date'][i])==float:
        print("Current Status: {}".format(sf_building_permits['Current Status'][i]))

In [19]:
#replace missing data in 'Issued Date' with 'Not Issued yet'
sf_building_permits = sf_building_permits.fillna(value={'Issued Date':'Not Issued yet'})

In [21]:
#frequency of missing values in each columns
percent_null = sf_building_permits.isnull().sum()
(percent_null*100)/len(sf_building_permits)

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Name                                0.000000
Street Suffix                              1.391654
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                0.000000
Completed Date                             0.000000
First Construction Document Date           7.514329
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

In [22]:
sf_building_permits[['Current Status','First Construction Document Date','Issued Date']]

       Current Status First Construction Document Date     Issued Date
0             expired                       11/09/2015      11/09/2015
1              issued                       08/03/2017      08/03/2017
2           withdrawn                              NaN  Not Issued yet
3            complete                       07/18/2017      07/18/2017
4              issued                       11/20/2017      12/01/2017
5              issued                       07/06/2017      07/06/2017
6            complete                       06/30/2017      06/30/2017
7              issued                       06/30/2017      06/30/2017
8              issued                       07/05/2017      07/05/2017
9              issued                       07/06/2017      07/06/2017
10             issued                       07/06/2017      07/06/2017
11             issued                       07/07/2017      07/07/2017
12             issued                       07/10/2017      07/10/2017
13              filed                              NaN  Not Issued yet
14             issued                       07/26/2017      07/26/2017
15             issued                       07/27/2017      07/27/2017
16             issued                       07/27/2017      07/27/2017
17             issued                       07/27/2017      07/27/2017
18              filed                              NaN  Not Issued yet
19             issued                       07/28/2017      07/28/2017
20             issued                       07/31/2017      07/31/2017
21              filed                              NaN  Not Issued yet
22              filed                              NaN  Not Issued yet
23             issued                       08/07/2017      08/07/2017
24             issued                       08/08/2017      08/08/2017
25             issued                       08/16/2017      08/16/2017
26             issued                       08/18/2017      08/18/2017
27             issued                       08/21/2017      08/21/2017
28             issued                       08/21/2017      08/21/2017
29             issued                       08/22/2017      08/22/2017
...               ...                              ...             ...
198870         issued                       02/23/2018      02/23/2018
198871         issued                       02/23/2018      02/23/2018
198872          filed                              NaN  Not Issued yet
198873         issued                       02/23/2018      02/23/2018
198874         issued                       02/23/2018      02/23/2018
198875          filed                              NaN  Not Issued yet
198876         issued                       02/23/2018      02/23/2018
198877         issued                       02/23/2018      02/23/2018
198878          filed                              NaN  Not Issued yet
198879         issued                       02/23/2018      02/23/2018
198880         issued                       02/23/2018      02/23/2018
198881         issued                       02/23/2018      02/23/2018
198882         issued                       02/23/2018      02/23/2018
198883         issued                       02/23/2018      02/23/2018
198884          filed                              NaN  Not Issued yet
198885          filed                              NaN  Not Issued yet
198886       approved                              NaN  Not Issued yet
198887       complete                       11/03/2017      11/03/2017
198888       complete                       10/12/2017      10/12/2017
198889       complete                       10/24/2017      10/24/2017
198890          filed                              NaN  Not Issued yet
198891         issued                       12/08/2017      12/08/2017
198892         issued                       01/16/2018      01/16/2018
198893       complete                       12/05/2017      12/05/2017
198894         issued                       12/05/2017      12/05/2017
198895         issued                       12/05/2017      12/05/2017
198896         issued                       12/06/2017      12/06/2017
198897         issued                       12/06/2017      12/06/2017
198898         issued                       12/06/2017      12/06/2017
198899         issued                       12/07/2017      12/07/2017

[198900 rows x 3 columns]

In [23]:
#we see that the missing values in the 'First Construction Document Date' correspond with the "not issued values"
#this shows that the missing values are NMAR
#construction begins only after date of issue
#fill in missing values in 'First Construction Document Date' with "Not Issued yet"
list_of_null=[]
for index in range(len(sf_building_permits)):
    if (type(sf_building_permits['First Construction Document Date'][index]) == float):
        list_of_null.append(index)

In [24]:
#It is seen that some of the values are missing even after the date of issue has been given. 
list_of_missing = []
for index in list_of_null:
    if not (sf_building_permits['Issued Date'][index]) == "Not Issued yet":
        list_of_missing.append(index)
        print(index,sf_building_permits['Issued Date'][index],sf_building_permits['First Construction Document Date'][index])

11843 12/24/2013 nan
11845 12/24/2013 nan
12966 05/30/2013 nan
14261 05/20/2016 nan
14362 06/13/2013 nan
15022 06/07/2013 nan
15847 06/14/2013 nan
24416 12/13/2013 nan
29462 10/29/2013 nan
33961 12/16/2013 nan
34152 12/17/2013 nan
71214 01/26/2015 nan
86318 05/20/2015 nan
97574 09/02/2015 nan
125041 05/24/2016 nan
125118 05/24/2016 nan
125120 05/24/2016 nan
125121 05/24/2016 nan
125123 05/24/2016 nan
125126 05/24/2016 nan
125128 05/24/2016 nan
125129 05/24/2016 nan
125130 05/24/2016 nan
125131 05/24/2016 nan
125132 05/24/2016 nan
125133 05/24/2016 nan
125138 05/24/2016 nan
125140 05/24/2016 nan
125177 05/24/2016 nan
125396 05/25/2016 nan
135185 08/31/2016 nan
177278 06/16/2017 nan

In [25]:
#Seperate out the NMAR values from the MAR values
for i in list_of_null:
    if i in list_of_missing:
        list_of_null.remove(i)

In [26]:
#Replace the NMAR values with "Not issued yet"
sf_building_permits['First Construction Document Date'][list_of_null]="Not Issued yet"

In [27]:
#frequency of missing values in each columns. We see that the "First construction Date" column has reduced to 0.1%
percent_null = sf_building_permits.isnull().sum()
(percent_null*100)/len(sf_building_permits)

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Name                                0.000000
Street Suffix                              1.391654
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                0.000000
Completed Date                             0.000000
First Construction Document Date           0.012569
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

In [63]:
#we can see form the percentage of missing columns and the data goven below that the "Proposed no of stories" and the "Existing stories" columns are hightly correlated with each other
sf_building_permits[['Number of Existing Stories','Number of Proposed Stories']].corr()

,Number of Existing Stories,Number of Proposed Stories
Number of Existing Stories,1.000000,0.985817
Number of Proposed Stories,0.985817,1.000000

In [65]:
#We see that the "proposed no. of stories" is almost always equal to the "existing no. of stories" column.
#This tells us that either the existing no. of stories were enough, the existing stories were built according to plan
#or that the building wasn't created/completed
sf_building_permits[['Current Status','Number of Proposed Stories','Number of Existing Stories']]

       Current Status  Number of Proposed Stories  Number of Existing Stories
0             expired                         NaN                         6.0
1              issued                         NaN                         7.0
2           withdrawn                         6.0                         6.0
3            complete                         2.0                         2.0
4              issued                         NaN                         3.0
5              issued                         5.0                         5.0
6            complete                         3.0                         3.0
7              issued                         NaN                         3.0
8              issued                         NaN                         3.0
9              issued                         NaN                         3.0
10             issued                         NaN                         3.0
11             issued                         NaN                         3.0
12             issued                         NaN                         3.0
13              filed                         2.0                         2.0
14             issued                         NaN                         3.0
15             issued                         NaN                         3.0
16             issued                         NaN                         3.0
17             issued                         NaN                         3.0
18              filed                         4.0                         4.0
19             issued                         NaN                         3.0
20             issued                         NaN                         3.0
21              filed                         2.0                         2.0
22              filed                         3.0                         3.0
23             issued                         NaN                         3.0
24             issued                         4.0                         4.0
25             issued                         2.0                         2.0
26             issued                         NaN                         3.0
27             issued                         NaN                         3.0
28             issued                         NaN                         3.0
29             issued                         NaN                         3.0
...               ...                         ...                         ...
198870         issued                         NaN                         3.0
198871         issued                         NaN                         3.0
198872          filed                         2.0                         2.0
198873         issued                         2.0                         2.0
198874         issued                         3.0                         3.0
198875          filed                         5.0                         3.0
198876         issued                         NaN                         3.0
198877         issued                         2.0                         2.0
198878          filed                         2.0                         2.0
198879         issued                         2.0                         2.0
198880         issued                         NaN                         3.0
198881         issued                         NaN                         3.0
198882         issued                         2.0                         2.0
198883         issued                         NaN                         3.0
198884          filed                         NaN                         3.0
198885          filed                         2.0                         2.0
198886       approved                         3.0                         3.0
198887       complete                         4.0                         4.0
198888       complete                         9.0                         9.0
198889       complete                         1.0                         1.0
198890          filed                         6.0                         6.0
198891         issued                         2.0                         2.0
198892         issued                         3.0                         3.0
198893       complete                         3.0                         3.0
198894         issued                         2.0                         2.0
198895         issued                         NaN                         3.0
198896         issued                         4.0                         4.0
198897         issued                         NaN                         3.0
198898         issued                         NaN                         3.0
198899         issued                         NaN                         3.0

[198900 rows x 3 columns]

In [71]:
#first way to impute data
from sklearn.preprocessing import Imputer

imp = Imputer(missing_values="NaN", strategy='median', axis=0)
X = imp.fit_transform(sf_building_permits[['Number of Existing Stories']])

In [68]:
#creating a test data frame and replacing the "Existing no. of stories" column with the median value
#Imputation using Imputer function
sf_building_permits_1 = sf_building_permits
sf_building_permits_1[['Number of Existing Stories']]=pd.DataFrame(X, columns=['Number of Existing Stories'])
sf_building_permits_1[['Current Status','Number of Proposed Stories','Number of Existing Stories']]

       Current Status  Number of Proposed Stories  Number of Existing Stories
0             expired                         NaN                         6.0
1              issued                         NaN                         7.0
2           withdrawn                         6.0                         6.0
3            complete                         2.0                         2.0
4              issued                         NaN                         3.0
5              issued                         5.0                         5.0
6            complete                         3.0                         3.0
7              issued                         NaN                         3.0
8              issued                         NaN                         3.0
9              issued                         NaN                         3.0
10             issued                         NaN                         3.0
11             issued                         NaN                         3.0
12             issued                         NaN                         3.0
13              filed                         2.0                         2.0
14             issued                         NaN                         3.0
15             issued                         NaN                         3.0
16             issued                         NaN                         3.0
17             issued                         NaN                         3.0
18              filed                         4.0                         4.0
19             issued                         NaN                         3.0
20             issued                         NaN                         3.0
21              filed                         2.0                         2.0
22              filed                         3.0                         3.0
23             issued                         NaN                         3.0
24             issued                         4.0                         4.0
25             issued                         2.0                         2.0
26             issued                         NaN                         3.0
27             issued                         NaN                         3.0
28             issued                         NaN                         3.0
29             issued                         NaN                         3.0
...               ...                         ...                         ...
198870         issued                         NaN                         3.0
198871         issued                         NaN                         3.0
198872          filed                         2.0                         2.0
198873         issued                         2.0                         2.0
198874         issued                         3.0                         3.0
198875          filed                         5.0                         3.0
198876         issued                         NaN                         3.0
198877         issued                         2.0                         2.0
198878          filed                         2.0                         2.0
198879         issued                         2.0                         2.0
198880         issued                         NaN                         3.0
198881         issued                         NaN                         3.0
198882         issued                         2.0                         2.0
198883         issued                         NaN                         3.0
198884          filed                         NaN                         3.0
198885          filed                         2.0                         2.0
198886       approved                         3.0                         3.0
198887       complete                         4.0                         4.0
198888       complete                         9.0                         9.0
198889       complete                         1.0                         1.0
198890          filed                         6.0                         6.0
198891         issued                         2.0                         2.0
198892         issued                         3.0                         3.0
198893       complete                         3.0                         3.0
198894         issued                         2.0                         2.0
198895         issued                         NaN                         3.0
198896         issued                         4.0                         4.0
198897         issued                         NaN                         3.0
198898         issued                         NaN                         3.0
198899         issued                         NaN                         3.0

[198900 rows x 3 columns]

In [72]:
#data imputation using cross validation

import numpy as np
import pylab as pl

In [73]:
#sf_building_permits_new[['Number of Existing Stories']] = sf_building_permits_1[['Number of Existing Stories']]
df = sf_building_permits[['Number of Existing Stories','Number of Proposed Stories']]

In [74]:
is_test = np.random.uniform(0, 1, len(df)) > 0.75
train = df[is_test==False]
test = df[is_test==True]

In [75]:
len(train), len(test)

(149650, 49250)

In [76]:
from sklearn.neighbors import KNeighborsRegressor

story_imputer = KNeighborsRegressor(n_neighbors=2000)

#split our data into 2 groups; data containing nulls and data 
# not containing nulls we'll train on the latter and make
# 'predictions' on the null data to impute monthly_income
train_w_proposed_stories = train[train['Number of Proposed Stories'].isnull()==False]
train_w_null_proposed_stories = train[train['Number of Proposed Stories'].isnull()==True]

In [77]:
train_w_proposed_stories

        Number of Existing Stories  Number of Proposed Stories
2                              6.0                         6.0
13                             2.0                         2.0
21                             2.0                         2.0
24                             4.0                         4.0
33                             3.0                         3.0
42                             3.0                         3.0
48                             2.0                         2.0
68                             2.0                         2.0
82                             3.0                         3.0
83                             3.0                         5.0
89                             3.0                         3.0
91                             2.0                         2.0
93                             1.0                         1.0
94                             2.0                         2.0
96                             3.0                         3.0
97                             1.0                         1.0
98                             2.0                         2.0
101                            2.0                         2.0
102                            4.0                         4.0
103                            2.0                         2.0
105                            1.0                         1.0
106                            4.0                         4.0
107                            2.0                         2.0
108                            3.0                         3.0
110                            3.0                         3.0
111                            3.0                         3.0
112                            2.0                         2.0
113                            2.0                         2.0
114                            2.0                         2.0
116                            2.0                         2.0
...                            ...                         ...
198832                         4.0                         4.0
198834                         1.0                         1.0
198835                         1.0                         1.0
198838                        38.0                        38.0
198839                        38.0                        38.0
198845                        16.0                        16.0
198846                         2.0                         2.0
198849                        43.0                        43.0
198853                         2.0                         2.0
198855                         3.0                         3.0
198856                        52.0                        52.0
198863                         3.0                         3.0
198864                         4.0                         4.0
198866                         2.0                         2.0
198867                         6.0                         6.0
198873                         2.0                         2.0
198874                         3.0                         3.0
198875                         3.0                         5.0
198877                         2.0                         2.0
198878                         2.0                         2.0
198879                         2.0                         2.0
198882                         2.0                         2.0
198886                         3.0                         3.0
198887                         4.0                         4.0
198888                         9.0                         9.0
198889                         1.0                         1.0
198891                         2.0                         2.0
198892                         3.0                         3.0
198893                         3.0                         3.0
198896                         4.0                         4.0

[117442 rows x 2 columns]

In [78]:
train_w_null_proposed_stories

        Number of Existing Stories  Number of Proposed Stories
4                              3.0                         NaN
7                              3.0                         NaN
9                              3.0                         NaN
10                             3.0                         NaN
11                             3.0                         NaN
15                             3.0                         NaN
17                             3.0                         NaN
19                             3.0                         NaN
20                             3.0                         NaN
23                             3.0                         NaN
26                             3.0                         NaN
27                             3.0                         NaN
28                             3.0                         NaN
30                             3.0                         NaN
31                             3.0                         NaN
32                             3.0                         NaN
34                             3.0                         NaN
36                             3.0                         NaN
38                             3.0                         NaN
44                             3.0                         NaN
47                             3.0                         NaN
49                             3.0                         NaN
50                             3.0                         NaN
52                             3.0                         NaN
54                             3.0                         NaN
55                             3.0                         NaN
56                             3.0                         NaN
57                             3.0                         NaN
58                             3.0                         NaN
59                             3.0                         NaN
...                            ...                         ...
198757                         3.0                         NaN
198777                         3.0                         NaN
198811                         3.0                         NaN
198818                         3.0                         NaN
198819                         3.0                         NaN
198821                         3.0                         NaN
198822                         3.0                         NaN
198824                         3.0                         NaN
198830                         3.0                         NaN
198831                         3.0                         NaN
198833                         3.0                         NaN
198836                         2.0                         NaN
198837                         3.0                         NaN
198840                         3.0                         NaN
198842                         3.0                         NaN
198847                         3.0                         NaN
198848                         3.0                         NaN
198861                         3.0                         NaN
198862                         3.0                         NaN
198865                         3.0                         NaN
198868                         3.0                         NaN
198869                         3.0                         NaN
198870                         3.0                         NaN
198876                         3.0                         NaN
198883                         3.0                         NaN
198884                         3.0                         NaN
198895                         3.0                         NaN
198897                         3.0                         NaN
198898                         3.0                         NaN
198899                         3.0                         NaN

[32208 rows x 2 columns]

In [79]:
train_w_proposed_stories.corr()

,Number of Existing Stories,Number of Proposed Stories
Number of Existing Stories,1.000000,0.985439
Number of Proposed Stories,0.985439,1.000000

In [80]:
train_w_proposed_stories.corr().ix[:,1]

Number of Existing Stories    0.985439
Number of Proposed Stories    1.000000
Name: Number of Proposed Stories, dtype: float64

In [81]:
cols = ['Number of Existing Stories']
story_imputer=story_imputer.fit(train_w_proposed_stories[cols], train_w_proposed_stories['Number of Proposed Stories'])

In [82]:
new_values = story_imputer.predict(train_w_null_proposed_stories[cols])

In [83]:
new_values=np.around(new_values)

In [84]:
train_w_null_proposed_stories['Number of Proposed Stories'] = new_values

In [85]:
train = train_w_proposed_stories.append(train_w_null_proposed_stories)
len(train)

149650

In [86]:
test['Number of Proposed Stories'] = story_imputer.predict(test[cols])
test.head()

   Number of Existing Stories  Number of Proposed Stories
0                         6.0                      5.9995
1                         7.0                      6.8490
3                         2.0                      2.0360
5                         5.0                      4.9995
6                         3.0                      3.1805

In [56]:
#list1 = new_values.tolist()

In [57]:
#myFormattedList = [ '%.0f' % elem for elem in list1 ]